"""init

Revision ID: c695213a2826
Revises: 
Create Date: 2021-12-01 15:53:38.977230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c695213a2826"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_station",
        sa.Column("station_id", sa.String(length=10), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column(
            "latitude", sa.Numeric(precision=10, scale=7), nullable=False
        ),
        sa.Column(
            "longitude", sa.Numeric(precision=10, scale=7), nullable=False
        ),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("station_id"),
    )
    op.create_table(
        "forecast_data",
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("station_id", sa.String(length=10), nullable=False),
        sa.Column("cloud_cover", sa.Integer(), nullable=True),
        sa.Column(
            "condition",
            postgresql.ENUM(
                "dry",
                "fog",
                "rain",
                "sleet",
                "snow",
                "hail",
                "thunderstorm",
                name="weathercondition",
            ),
            nullable=True,
        ),
        sa.Column("dew_point", sa.Float(), nullable=True),
        sa.Column("precipitation", sa.Float(), nullable=True),
        sa.Column("pressure_msl", sa.Float(), nullable=True),
        sa.Column("relative_humidity", sa.Float(), nullable=True),
        sa.Column("sunshine", sa.Float(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("visibility", sa.Float(), nullable=True),
        sa.Column("wind_direction", sa.Float(), nullable=True),
        sa.Column("wind_speed", sa.Float(), nullable=True),
        sa.Column("wind_gust_direction", sa.Float(), nullable=True),
        sa.Column("wind_gust_speed", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["weather_station.station_id"],
        ),
        sa.PrimaryKeyConstraint("time", "station_id"),
        sa.UniqueConstraint("time", "station_id"),
    )
    op.create_table(
        "weather_data",
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("station_id", sa.String(length=10), nullable=False),
        sa.Column("cloud_cover", sa.Integer(), nullable=True),
        sa.Column(
            "condition",
            postgresql.ENUM(
                "dry",
                "fog",
                "rain",
                "sleet",
                "snow",
                "hail",
                "thunderstorm",
                name="weathercondition",
            ),
            nullable=True,
        ),
        sa.Column("dew_point", sa.Float(), nullable=True),
        sa.Column("precipitation", sa.Float(), nullable=True),
        sa.Column("pressure_msl", sa.Float(), nullable=True),
        sa.Column("relative_humidity", sa.Float(), nullable=True),
        sa.Column("sunshine", sa.Float(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("visibility", sa.Float(), nullable=True),
        sa.Column("wind_direction", sa.Float(), nullable=True),
        sa.Column("wind_speed", sa.Float(), nullable=True),
        sa.Column("wind_gust_direction", sa.Float(), nullable=True),
        sa.Column("wind_gust_speed", sa.Float(), nullable=True),
        sa.Column("is_historical", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["weather_station.station_id"],
        ),
        sa.PrimaryKeyConstraint("time", "station_id"),
        sa.UniqueConstraint("time", "station_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_data")
    op.drop_table("forecast_data")
    op.drop_table("weather_station")
    # ### end Alembic commands ###
